# Add your imprint or brand name here, it will appear in navigation.
publisher: "Book Dash"

# Your publisher name will link to this URL in navigation.
publisher-url: "http://bookdash.org"

# The name of the series of books in this folder.
name: "Book Dash ebooks"

# A one-liner about this series. Useful for Open Graph metadata.
description: "Ebooks from Book Dash: new, African children's books that anyone can freely download, translate and distribute."

# The primary language used in this series. You can set the language for each book individually below at 'defaults'. 
# To understand what language tags to use, read: http://www.w3.org/International/articles/language-tags/ 
# For the registry of tags: http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry 
# Useful lookup tool: http://r12a.github.io/apps/subtags/
language: en

# Leave this unchanged as http://localhost:4000 unless you really know what you're doing here. This is the URL that Jekyll will run at by default locally.
url: http://localhost:4000

# Change this to the name of your series folder, e.g. /my-cool-books
baseurl: /bookdash-books

# Leave this unchanged as kramdown unless you really know how and why to change your markdown processor
markdown: kramdown

# Leave this unchanged as none. This way, your book's chapters will all generate correctly named in one folder.
# This is really useful for grabbing allyour HTML files at once for including in epubs or sending to PrinceXML.
permalink: none

# Leave this unchanged. It tells Jekyll where to find Sass partials. (See http://jekyllrb.com/docs/assets/#sassscss)
sass:
    sass_dir: css/_sass

# These are default YAML values that apply to multiple documents. (For technical details, see http://jekyllrb.com/docs/configuration/#front-matter-defaults).
defaults: 
    -   # Defaults for all books
        scope: 
            path: ""
        values:
            language: "en"
            layout: "default"
#            layout: "epub"
            stylesheet-print: "print-bookdash.css"
            stylesheet-web: "web-bookdash.css"
            stylesheet-epub: "epub-bookdash.css"
            style: "chapter"
            contents: "index.html"
            language: "en"
            images-folder: images
    -   # Defaults for all editions of a book
        scope:
            path: "sleepy-mr-sloth"
        values:
            book-title-en: ""  # Title in English
            illustrator: "Graham Paterson"
            writer: "Paul Kennedy"
            designer: "Nick Mulgrew"
            book-title: "Sleepy Mr Sloth"
            book-dash-day: "Cape Town 10 May 2014"
            publication-date: "2014-05-10"
    -   # Defaults for each language
        scope:
            path: "sleepy-mr-sloth/en"
        values:
            language: "en"
            isbn-print: ""
            isbn-epub: ""
            uuid: ""
            translator: ""
    -   # Defaults for all editions of a book
        scope:
            path: "a-fish-and-a-gift"
        values:
            book-title-en: "A Fish and a Gift" # Title in English
            illustrator: "Jesse Breytenbach"
            writer: "Liesl Jobson"
            designer: "Andy Thesen"
            book-dash-day: "Cape Town 28 June 2014"
    -   # Defaults for each language
        scope:
            path: "a-fish-and-a-gift/en"
        values:
            book-title: ""  # Leave blank for English editions
            language: "en" # Use ISO language codes, preferably two-letter
            isbn-print: ""
            isbn-epub: ""
            uuid: ""
            translator: ""
    -   
        scope:
            path: "a-fish-and-a-gift/zu"
        values:
            book-title: "Inhlanzi Nesipho"  # Leave blank for English editions
            language: "zu"  # Use ISO language codes, preferably two-letter
            isbn-print: ""
            isbn-epub: ""
            uuid: ""
            translator: ""
