name: "Book Dash books"
description: "Jekyll setup for turning markdown into HTML for Book Dash books, see http://bookdash.org"

url: http://localhost:4000
baseurl: /bookdash-books

paginate: 10

markdown: kramdown
permalink: none
highlighter: pygments